### ISSUE TITLE
Inquiry about logo

### ISSUE THREAD

**Issue by haggen88** [SebastJava/linuxmint-logo#1]
First of all congratulate you on the new Mint logo, it looks great!. 
I have a question with the file "Logo-Ring-Filled- # 000.svg", in the case of using the logo [white border] on a white background the circumference is lost and the proportions change.  Have you thought about adding a thin dark border and / or shadow?

Regards

P.S.   At the moment you have not defined the colors or is it still the same green [RGB: 134/190/67]?

**Comment by SebastJava** [comment]
I will start doing a few updates on this repository, related to your questions. I should be back with answers sometime today.

**Comment by SebastJava** [comment]
Okay, now i updated the README.md here. There you will find some sort of answer to your second question, about the color. See the "Color" subtitle. And the answer to your first question should be posted here within 48 hours.

**Comment by SebastJava** [comment]
I did a big update. Almost every file got re-edited.
Check, you should find what you were looking for. Do you like it?
There is still no color there. It is all black and white. Ask if you need some help.

**Comment by SebastJava** [comment]
I created a **special-requests** directory just for you. How does this looks? I exported PNGs to 320px X 320px, that’s kind of low resolution. You could just open these SVGs in Inkscape and scale them to your needs, and then export. I used the "official" color: #86BE43.

**Comment by haggen88** [comment]
Looks great!
